apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: earny-be
spec:
  # type: LoadBalancer
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
