apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: earny-fe
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment  # Update this with your actual Deployment name
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
